### ISSUE TITLE
Linux AppImage stuck on blank white screen

### ISSUE THREAD

**Issue by deltadex7** [mkpoli/paletteworks-editor#8]
When running the app using AppImage, it shows blank white screen. Since it uses Tauri for desktop clients instead of Electron, I can't access dev tools to get any logs. Also running from command line doesn't output anything.

![PaletteWorks Editor shows blank white screen](https://user-images.githubusercontent.com/54788149/218260170-fba2f3ae-f729-4a8f-aead-36f460344772.png)

I am running on Fedora Kinoite 37, KDE Plasma 5.26.5, Wayland.

P.S. This also happens on Arch Linux.

**Comment by ChobojaX** [comment]
Hyprland(Wayland) and i3(X11) on arch linux also have this problem

**Comment by mkpoli** [comment]
Sorry for late reply over a year and a half.

I believe this is fixed by v1.11.1 (490c7f5e4cfc8dd80897fbaaa6c904cfe40b3bc1) by updating tauri to version 1.0.0.

However it seems that Ubuntu 20.04 is not supported anymore.
